spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pangolin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: fyh
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/configuration/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

token:
  secretKey: dbiu2y374g3287d2xaewd97defqdc8d9
  expiration: 259200    # 三天后